global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'product-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['product-service:8089']

  - job_name: 'order-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['order-service:3000']

  - job_name: 'client-api'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'client-api-app:8081' ]

