name: Analyze Product Service with SonarQube

on:
  push:
    paths:
      - 'product-service/**'
  pull_request:
    paths:
      - 'product-service/**'

jobs:
  sonar:
    name: SonarQube Analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven

      - name: Run SonarQube analysis
        working-directory: ./product-service
        run: mvn verify sonar:sonar -Dsonar.projectKey=product-service \
                                  -Dsonar.host.url=http://host.docker.internal:9000 \
                                  -Dsonar.login=${{ secrets.SONAR_TOKEN }}
